### ISSUE TITLE
The dll links to msvcp140d.dll, not to msvcp140.dll.

### ISSUE THREAD

**Issue by moriyac** [tvn-cosine/tvn-cosine#11]
Your tesseract.net nuget library is very helpful for me. Thank you for your great work. 

This post reports thing I noticed. 
The cpp library included by tesseract.net 4.0.0.6 links to msvcp140d.dll, not to msvcp140.dll. 
The msvcp140d.dll is only contained by Visual C++ tools option of Visual Studio, not contained by Visual C++ Redistributable Package. It contains debuging symbols for developers. 
Visual C++ Redistributable Package contains msvcp140.dll.
So, your tesseract.net nuget library is available only for the developers using VC++ feature. 

I wish you rebuild these libraries in order to be available for any user using VC++ redistributable libraries only. 

Thank you. 
![depends_screenshot](https://user-images.githubusercontent.com/30452593/34546222-c7e50d4e-f135-11e7-8b56-4ab67fecd33c.png)

**Comment by tvn-cosine** [comment]
Hi moriyac

Please try to build your own Tesseract dll using these steps at
[(https://github.com/tesseract-ocr/tesseract/wiki/Compiling#windows)]((https://github.com/tesseract-ocr/tesseract/wiki/Compiling#windows))

Set the project to release.  I believe this will resolve your issue.

Regards,

**Comment by moriyac** [comment]
Hello tvn-cosine, 

OK. I will try it.
Thank you for your response.

**Comment by tvn-cosine** [comment]
Please download latest version and test.  Latest version does include breaking changes, so beware.
