### ISSUE TITLE
Can we use opencv Mat format for image input?

### ISSUE THREAD

**Issue by newonejoe** [tvn-cosine/tvn-cosine#6]
Hi, thanks a lot for the .Net wrapper for tesseract 4.0. I am also using the opencv for target detection and image crop. Do you have any idea to make it available to use the Mat as input?

```
        private TessBaseAPI _ocr;
        public VisionOCR(string dataPath)
        {
            _ocr = new TessBaseAPI(dataPath, "eng", OcrEngineMode.TESSERACT_ONLY);
            _ocr.SetVariable("tessedit_char_whitelist", "1234567890s.");
        }
        protected override void DisposeObject()
        {
            _ocr.Dispose();
        }
        public string DoOcr(Mat target)
        {
            _ocr.Recognize(target);
            return _ocr.GetUTF8Text();
        }
```

**Comment by tvn-cosine** [comment]
Hi, 

The latest release -Version 4.0.0.6 should be able to accept mat images.  This can be found here: [https://www.nuget.org/packages/tesseract.net/4.0.0.6](url)

It however is still only working on pointers without any pretty wrappers supplied.  Please read up on this thread [https://stackoverflow.com/a/8126992](url) for more info on the mat::data pointer.  Maybe this [http://www.emgu.com/wiki/files/3.1.0/document/html/75321c1c-8376-ff13-ebdc-9c08b1c052c5.htm](url) will assist you to get access to the actual pointer.

It is also important to note that this has not been tested thoroughly.  The current method is implemented as a pointer pass through to the TessBaseApi.  As Tesseract has been implemented using the Leptonica library, we focussed on that. 

Regards,
The tvn-cosine team
