### ISSUE TITLE
tvn-cosine.ocr.tesseract/

### ISSUE THREAD

**Issue by bruceburge** [tvn-cosine/tvn-cosine#7]
Project won't build, removed dlls are still referenced in project as content, and are listed in the test project.

pvt.cppan.demo.google.tesseract.libtesseract400.dll doesn't appear to have been uploaded into repo.

**Comment by tvn-cosine** [comment]
Hi

Download the latest version.  Uninstall/Reinstall nugets if lib folder is not displaying.  The lib folders on demo and test have been removed in an effort to reduce download requirements of project.

Regards,
the tvn-cosine team
