### ISSUE TITLE
Best traineddata doesn't seem to work with current nuget package

### ISSUE THREAD

**Issue by whatohyou** [tvn-cosine/tvn-cosine#8]
When I tried to use trained data from here,
https://github.com/tesseract-ocr/tessdata/blob/master/best/jpn_vert.traineddata

renamed as jpn.traineddata and copied to 
@"./tessdata";
folder then,

{                
                string dataPath = @"./tessdata";
                string language = @"jpn";
using (var api = new TessBaseAPI(dataPath, language, OcrEngineMode.LSTM_ONLY, PageSegmentationMode.SINGLE_BLOCK))
{
 api.SetInputImage(testImagePath);
                    string text = api.GetUTF8Text();
                    RTB1.Text = text;
                    Clipboard.SetText(text);
                }                
            }

Then when I run the program, I get application crashes. It says program tried to read/write protected memory.

When I change the traineddata back to original 43 Mb file then it doesn't crash the application.

However, old traineddata is not trained for vertical japanese so it is useless.

Is there any solution?

**Comment by tvn-cosine** [comment]
Believe it is the version 4 of Tesseract dll that is causing the crash.  Will have a look at the best approach to make the project backwards compatible.  If backwards compatibility is not feasible we will look at creating a tool that can convert the models to the latest standards.

**Comment by tvn-cosine** [comment]
Please download this version from nuget:

[https://www.nuget.org/packages/tesseract.net/3.5.1.2](https://www.nuget.org/packages/tesseract.net/3.5.1.2)
