### ISSUE TITLE
Recognize many pictures not working

### ISSUE THREAD

**Issue by AndrewIva** [tvn-cosine/tvn-cosine#9]
Hi!
When I tried to recognize many pictures, I have exception AccessViolationException. It seems tesseract dispose pix before wrapper api. Maybe i do somthing wrong. 
Here is code example.

```
 static void Main(string[] args)
        {
            Leptonica.Pix pix = Pix.Read(@"./1.jpg");

            Leptonica.Box rect = BoxBasic.boxCreate(100, 100 , 800, 300);

            Pix pixFragment = pix.pixClipRectangle(rect, ref rect);
            Tesseract.TessBaseAPI engine = new Tesseract.TessBaseAPI(@"./tessdata", "rus");
             
            engine.SetInputImage(pixFragment);
            engine.Recognize();
            
            string text = engine.GetUTF8Text();
            //engine.DisposeImage();
            Console.WriteLine(text);

            Console.WriteLine("===================================");

            pixFragment = pix.pixClipRectangle(rect, ref rect);
            engine.SetInputImage(pixFragment);
            engine.Recognize();

            text = engine.GetUTF8Text();
            Console.WriteLine(text);
        }
```

**Comment by tvn-cosine** [comment]
Looks like a Marshaling \ logic bug in method:
 `public void SetInputImage(Pix value)  { }`

Will look at the problem, but in the mean time please test the process method by supplying image path from disk.
`public ResultIterator Process(string inputFile, bool createPdf = false) {}`

**Comment by tvn-cosine** [comment]
Please test with new release.  We have removed our own implementations to process clips from TessBaseApi.  All Tesseract methods still there.

Note: We have moved repository to 

[https://github.com/tvn-cosine/tesseract.net](https://github.com/tvn-cosine/tesseract.net)
